drop table if exists address;
drop table if exists phones;
drop table if exists client;

create table client
(
    id   bigserial not null primary key,
    name varchar(50),
    address_id bigint
);

create table address
(
    id   bigint generated by default as identity not null primary key,
    street varchar(50)
);

create table phones
(
    id   bigint generated by default as identity not null primary key,
    number varchar(50),
    client_id bigint references client(id)
);

delete from address;
insert into address(street) values ('street one');
insert into address(street) values ('street two');
insert into address(street) values ('street three');

delete from client;
insert into client(name, address_id) values ('First client',1);
insert into client(name, address_id) values('Second client',2);
insert into client(name, address_id) values('Third client',2);

delete from phones;
insert into phones(number, client_id) values ('3333', 1);
insert into phones(number, client_id) values ('456', 2);
insert into phones(number, client_id) values ('789', 2);