drop table if exists address;
drop table if exists phones;
drop table if exists client;
drop sequence if exists client_SEQ;

create sequence client_SEQ start with 1 increment by 1;

create table client
(
    id   bigserial not null primary key,
    name varchar(50),
    address_id bigint
);

create table address
(
    id   bigint generated by default as identity not null primary key,
    street varchar(50)
);

create table phones
(
    id   bigint generated by default as identity not null primary key,
    number varchar(50),
    client_id bigint references client(id)
);

alter sequence client_SEQ restart with 1;

delete from address;
insert into address(street) values ('ewrwrwer');
insert into address(street) values ('asdada');
insert into address(street) values ('sdfdgsf');

delete from client;
insert into client(name, address_id) values ('ssss',1);
insert into client(name, address_id) values('ffff',2);
insert into client(name, address_id) values('dddd',2);

delete from phones;
insert into phones(number, client_id) values ('3333', 1);
insert into phones(number, client_id) values ('4444', 2);