create sequence client_SEQ start with 1 increment by 1;

create table client
(
    id   bigint not null primary key,
    name varchar(50),
    address_id bigint
);

create table address
(
    id   bigint generated by default as identity not null primary key,
    street varchar(50)
);

create table phones
(
    id   bigint generated by default as identity not null primary key,
    number varchar(50),
    client_id bigint references client(id)
);